### ISSUE TITLE
Running clustered jetstream in kubernetes

### ISSUE THREAD

**Issue by eonward** [nats-io/jetstream#509]
When I try switching my jetstream deployment to clustered mode, my clients stop being able to interact with it.

I am wondering whether this is a config issue or something else.

I get this thrown back when I try to publish or subscribe (I'm using the Node client):

```
>> jetstream functionality in nats.js is preview functionality
NatsError: 503
    at Function.errorForCode (/nats-test/node_modules/nats/nats-base-client/error.ts:115:12)
    at Object.checkJsErrorCode (/nats-test/node_modules/nats/nats-base-client/jsutil.ts:98:24)
    at JetStreamClientImpl.parseJsResponse (/nats-test/node_modules/nats/nats-base-client/jsbaseclient_api.ts:106:19)
    at JetStreamClientImpl.<anonymous> (/nats-test/node_modules/nats/nats-base-client/jsbaseclient_api.ts:89:17)
    at Generator.next (<anonymous>)
    at fulfilled (/nats-test/node_modules/nats/lib/nats-base-client/jsbaseclient_api.js:19:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: '503',
  chainedError: Error: jetstream system temporarily unavailable
      at Object.checkJsErrorCode (/nats-test/node_modules/nats/nats-base-client/jsutil.ts:100:9)
      at JetStreamClientImpl.parseJsResponse (/nats-test/node_modules/nats/nats-base-client/jsbaseclient_api.ts:106:19)
      at JetStreamClientImpl.<anonymous> (/nats-test/node_modules/nats/nats-base-client/jsbaseclient_api.ts:89:17)
      at Generator.next (<anonymous>)
      at fulfilled (/nats-test/node_modules/nats/lib/nats-base-client/jsbaseclient_api.js:19:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
```

This is my config file

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-js-config
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222

    jetstream {
      store_dir: "/data/jetstream/store"
      max_file_store: 1G
    }

    server_name: "nats-server-0"

    cluster {
      name: "nats-js-cluster-0"
      port: 6222
      routes [
        nats://nats-js-0.nats.default.svc:6222
        nats://nats-js-1.nats.default.svc:6222
        nats://nats-js-2.nats.default.svc:6222
      ]

      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 30
    }

    leafnodes {
      remotes [
        {
          url: "nats://nats:7422"
        }
      ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nats-js
  labels:
    app: nats-js
spec:
  selector:
    app: nats-js
  clusterIP: None
  ports:
    - name: client
      port: 4222
    - name: cluster
      port: 6222
    - name: monitor
      port: 8222
    - name: metrics
      port: 7777
    - name: leafnodes
      port: 7422
    - name: gateways
      port: 7522
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-js
  labels:
    app: nats-js
spec:
  selector:
    matchLabels:
      app: nats-js
  replicas: 3
  serviceName: 'nats-js'
  volumeClaimTemplates:
    - metadata:
        name: nats-js-sts-vol
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: 'Filesystem'
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: nats-js
    spec:
      # Common volumes for the containers
      volumes:
        - name: config-volume
          configMap:
            name: nats-js-config
        - name: pid
          emptyDir: {}

      # Required to be able to HUP signal and apply config reload
      # to the server without restarting the pod.
      shareProcessNamespace: true

      #################
      #               #
      #  NATS Server  #
      #               #
      #################
      terminationGracePeriodSeconds: 60
      containers:
        - name: nats
          image: synadia/nats-server:nightly
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 7422
              name: leafnodes
            - containerPort: 6222
              name: cluster
            - containerPort: 8222
              name: monitor
            - containerPort: 7777
              name: metrics
          command:
            - 'nats-server'
            - '--config'
            - '/etc/nats-config/nats.conf'

          # Required to be able to define an environment variable
          # that refers to other environment variables.  This env var
          # is later used as part of the configuration file.
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_ADVERTISE
              value: $(POD_NAME).nats-js.$(POD_NAMESPACE).svc
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nats-config
            - name: pid
              mountPath: /var/run/nats
            - name: nats-js-sts-vol
              mountPath: /data/jetstream

          # Liveness/Readiness probes against the monitoring
          #
          livenessProbe:
            httpGet:
              path: /
              port: 8222
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8222
            initialDelaySeconds: 10
            timeoutSeconds: 5

          # Gracefully stop NATS Server on pod deletion or image upgrade.
          #
          lifecycle:
            preStop:
              exec:
                # Using the alpine based NATS image, we add an extra sleep that is
                # the same amount as the terminationGracePeriodSeconds to allow
                # the NATS Server to gracefully terminate the client connections.
                #
                command:
                  [
                    '/bin/sh',
                    '-c',
                    '/nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60',
                  ]
```

Any thoughts? 😶
